// don't ask do not ask

export const BAD_WORDS = [
    "fag",
    "faggot",
    "tranny",
    "trannie",
    "tannies",
    "ihate",
    "ihater",
    "trap",
    "nigars",
    "nigas",
    "nigg",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggahs",
    "niggar",
    "niggards",
    "niggars",
    "niggas",
    "niggaz",
    "nigger",
    "niggers",
    "nigglings",
    "niggor",
    "nigguh",
    "nigguhs",
    "niggur",
    "loli",
    "lolicon",
    "shota",
    "shotacon",
    "l0li",
    "l0l1",
    "5hota",
    "5hot4",
    "shot4",
    "5h0t4",
    "sh0t4",
    "sh0ta",
    "sho7a",
    "5ho7a",
    "slave",
    "master",
    "rape",
    "r4pe",
    "rap3",
    "r4p3",
    "fentanyl",
    "nword",
    "shemale",
    "ladyboy",
    "zigger",
    "4r5e",
    "5h1t",
    "5hit",
    "a55",
    "anal",
    "anus",
    "ar5e",
    "arrse",
    "arse",
    "ass",
    "ass-fucker",
    "asses",
    "assfucker",
    "assfukka",
    "asshole",
    "assholes",
    "asswhole",
    "a_s_s",
    "b!tch",
    "b00bs",
    "b17ch",
    "b1tch",
    "ballbag",
    "balls",
    "ballsack",
    "bastard",
    "beastial",
    "beastiality",
    "bellend",
    "bestial",
    "bestiality",
    "bi+ch",
    "biatch",
    "bitch",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchin",
    "bitching",
    "bloody",
    "blow job",
    "blowjob",
    "blowjobs",
    "boiolas",
    "bollock",
    "bollok",
    "boner",
    "boob",
    "boobs",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "breasts",
    "buceta",
    "bugger",
    "bum",
    "bunny fucker",
    "butt",
    "butthole",
    "buttmuch",
    "buttplug",
    "c0ck",
    "c0cksucker",
    "carpetmuncher",
    "cawk",
    "chink",
    "cipa",
    "cl1t",
    "clit",
    "clitoris",
    "clits",
    "cnut",
    "cock",
    "cock-sucker",
    "cockface",
    "cockhead",
    "cockmunch",
    "cockmuncher",
    "cocks",
    "cocksuck",
    "cocksucked",
    "cocksucker",
    "cocksucking",
    "cocksucks",
    "cocksuka",
    "cocksukka",
    "cok",
    "cokmuncher",
    "coksucka",
    "coon",
    "cox",
    "crap",
    "cum",
    "cummer",
    "cumming",
    "cums",
    "cumshot",
    "cunilingus",
    "cunillingus",
    "cunnilingus",
    "cunt",
    "cuntlick",
    "cuntlicker",
    "cuntlicking",
    "cunts",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cyberfucked",
    "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "d1ck",
    "damn",
    "dick",
    "dickhead",
    "dildo",
    "dildos",
    "dink",
    "dinks",
    "dirsa",
    "dlck",
    "dog-fucker",
    "doggin",
    "dogging",
    "donkeyribber",
    "doosh",
    "duche",
    "dyke",
    "ejaculate",
    "ejaculated",
    "ejaculates",
    "ejaculating",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "f u c k",
    "f u c k e r",
    "f4nny",
    "fag",
    "fagging",
    "faggitt",
    "faggot",
    "faggs",
    "fagot",
    "fagots",
    "fags",
    "fanny",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fatass",
    "fcuk",
    "fcuker",
    "fcuking",
    "feck",
    "fecker",
    "felching",
    "fellate",
    "fellatio",
    "fingerfuck",
    "fingerfucked",
    "fingerfucker",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "flange",
    "fook",
    "fooker",
    "fuck",
    "fucka",
    "fucked",
    "fucker",
    "fuckers",
    "fuckhead",
    "fuckheads",
    "fuckin",
    "fucking",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckme",
    "fucks",
    "fuckwhit",
    "fuckwit",
    "fudgepacker",
    "fuk",
    "fuker",
    "fukker",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "fux",
    "fux0r",
    "f_u_c_k",
    "gangbang",
    "gangbanged",
    "gangbangs",
    "gaylord",
    "gaysex",
    "goatse",
    "God",
    "god-dam",
    "god-damned",
    "goddamn",
    "goddamned",
    "hardcoresex",
    "hell",
    "heshe",
    "hoar",
    "hoare",
    "hoer",
    "homo",
    "hore",
    "horniest",
    "horny",
    "hotsex",
    "jack-off",
    "jackoff",
    "jap",
    "jerk-off",
    "jism",
    "jiz",
    "jizm",
    "jizz",
    "kawk",
    "knob",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "kock",
    "kondum",
    "kondums",
    "kum",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "l3i+ch",
    "l3itch",
    "labia",
    "lust",
    "lusting",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "masochist",
    "master-bate",
    "masterb8",
    "masterbat*",
    "masterbat3",
    "masterbate",
    "masterbation",
    "masterbations",
    "masturbate",
    "mo-fo",
    "mof0",
    "mofo",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "motherfuck",
    "motherfucked",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "muff",
    "mutha",
    "muthafecker",
    "muthafuckker",
    "muther",
    "mutherfucker",
    "n1gga",
    "n1gger",
    "nazi",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "niggers",
    "nob",
    "nobhead",
    "nobjocky",
    "numbnuts",
    "nutsack",
    "orgasim",
    "orgasims",
    "orgasm",
    "orgasms",
    "p0rn",
    "pawn",
    "pecker",
    "penis",
    "penisfucker",
    "phonesex",
    "phuck",
    "phuk",
    "phuked",
    "phuking",
    "phukked",
    "phukking",
    "phuks",
    "phuq",
    "pigfucker",
    "pimpis",
    "piss",
    "pissed",
    "pisser",
    "pissers",
    "pisses",
    "pissflaps",
    "pissin",
    "pissing",
    "pissoff",
    "poop",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "prick",
    "pricks",
    "pron",
    "pube",
    "pusse",
    "pussi",
    "pussies",
    "pussy",
    "pussys",
    "rectum",
    "retard",
    "rimjaw",
    "rimming",
    "shit",
    "s.o.b.",
    "sadist",
    "schlong",
    "screwing",
    "scroat",
    "scrote",
    "scrotum",
    "semen",
    "sex",
    "sh!+",
    "sh!t",
    "sh1t",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shemale",
    "shi+",
    "shit",
    "shitdick",
    "shite",
    "shited",
    "shitey",
    "shitfuck",
    "shitfull",
    "shithead",
    "shiting",
    "shitings",
    "shits",
    "shitted",
    "shitter",
    "shitters",
    "shitting",
    "shittings",
    "shitty",
    "skank",
    "slut",
    "sluts",
    "smegma",
    "smut",
    "snatch",
    "son-of-a-bitch",
    "spac",
    "spunk",
    "s_h_i_t",
    "t1tt1e5",
    "t1tties",
    "teets",
    "teez",
    "testical",
    "testicle",
    "titfuck",
    "tittie5",
    "tittiefucker",
    "titties",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tosser",
    "turd",
    "tw4t",
    "twat",
    "twathead",
    "twatty",
    "twunt",
    "twunter",
    "v14gra",
    "v1gra",
    "vagina",
    "viagra",
    "vulva",
    "w00se",
    "wang",
    "wank",
    "wanker",
    "wanky",
    "whoar",
    "whore",
    "willies",
    "willy",
    "xrated",
    "xxx",
    "blackpeople",
    "hitler",
    "n4zi",
    "n4z1",
    "naz1",
    "2g1c",
    "2girls1cup",
    "acrotomophilia",
    "alabamahotpocket",
    "alaskanpipeline",
    "anal",
    "anilingus",
    "anus",
    "apeshit",
    "arsehole",
    "ass",
    "asshole",
    "assmunch",
    "autoerotic",
    "autoerotic",
    "babeland",
    "babybatter",
    "babyjuice",
    "ballgag",
    "ballgravy",
    "ballkicking",
    "balllicking",
    "ballsack",
    "ballsucking",
    "bangbros",
    "bangbus",
    "bareback",
    "barelylegal",
    "barenaked",
    "bastard",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beavercleaver",
    "beaverlips",
    "beastiality",
    "bestiality",
    "bigblack",
    "bigbreasts",
    "bigknockers",
    "bigtits",
    "bimbos",
    "birdlock",
    "bitch",
    "bitches",
    "blackcock",
    "blondeaction",
    "blondeonblondeaction",
    "blowjob",
    "blowjob",
    "blowyourload",
    "bluewaffle",
    "blumpkin",
    "bollocks",
    "bondage",
    "boner",
    "boob",
    "boobs",
    "bootycall",
    "brownshowers",
    "brunetteaction",
    "bukkake",
    "bulldyke",
    "bulletvibe",
    "bullshit",
    "bunghole",
    "bunghole",
    "busty",
    "butt",
    "buttcheeks",
    "butthole",
    "cameltoe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpetmuncher",
    "carpetmuncher",
    "chocolaterosebuds",
    "cialis",
    "circlejerk",
    "clevelandsteamer",
    "clit",
    "clitoris",
    "cloverclamps",
    "clusterfuck",
    "cock",
    "cocks",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "coon",
    "coons",
    "creampie",
    "cum",
    "cumming",
    "cumshot",
    "cumshots",
    "cunnilingus",
    "cunt",
    "darkie",
    "daterape",
    "daterape",
    "deepthroat",
    "deepthroat",
    "dendrophilia",
    "dick",
    "dildo",
    "dingleberry",
    "dingleberries",
    "dirtypillows",
    "dirtysanchez",
    "doggiestyle",
    "doggiestyle",
    "doggystyle",
    "doggystyle",
    "dogstyle",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "donkeypunch",
    "doubledong",
    "doublepenetration",
    "dpaction",
    "dryhump",
    "dvda",
    "eatmyass",
    "ecchi",
    "ejaculation",
    "erotic",
    "erotism",
    "escort",
    "eunuch",
    "fag",
    "faggot",
    "fecal",
    "felch",
    "fellatio",
    "feltch",
    "femalesquirting",
    "femdom",
    "figging",
    "fingerbang",
    "fingering",
    "fisting",
    "footfetish",
    "footjob",
    "frotting",
    "fuck",
    "fuckbuttons",
    "fuckin",
    "fucking",
    "fucktards",
    "fudgepacker",
    "fudgepacker",
    "futanari",
    "gangbang",
    "gangbang",
    "gaysex",
    "genitals",
    "giantcock",
    "girlon",
    "girlontop",
    "girlsgonewild",
    "goatcx",
    "goatse",
    "goddamn",
    "gokkun",
    "goldenshower",
    "goodpoop",
    "googirl",
    "goregasm",
    "grope",
    "groupsex",
    "g-spot",
    "guro",
    "handjob",
    "handjob",
    "hardcore",
    "hardcore",
    "hentai",
    "homoerotic",
    "honkey",
    "hooker",
    "horny",
    "hotcarl",
    "hotchick",
    "howtokill",
    "howtomurder",
    "hugefat",
    "humping",
    "incest",
    "intercourse",
    "jackoff",
    "jailbait",
    "jailbait",
    "jellydonut",
    "jerkoff",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jizz",
    "juggs",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "knobbing",
    "leatherrestraint",
    "leatherstraightjacket",
    "lemonparty",
    "livesex",
    "lolita",
    "lovemaking",
    "makemecome",
    "malesquirting",
    "masturbate",
    "masturbating",
    "masturbation",
    "menageatrois",
    "milf",
    "missionaryposition",
    "mong",
    "motherfucker",
    "moundofvenus",
    "mrhands",
    "muffdiver",
    "muffdiving",
    "nambla",
    "nawashi",
    "negro",
    "neonazi",
    "nigga",
    "nigger",
    "nignog",
    "nimphomania",
    "nipple",
    "nipples",
    "nsfw",
    "nsfwimages",
    "nude",
    "nudity",
    "nutten",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "onecuptwogirls",
    "oneguyonejar",
    "orgasm",
    "orgy",
    "paedophile",
    "paki",
    "panties",
    "panty",
    "pedobear",
    "pedophile",
    "pegging",
    "penis",
    "phonesex",
    "pieceofshit",
    "pikey",
    "pissing",
    "pisspig",
    "pisspig",
    "playboy",
    "pleasurechest",
    "polesmoker",
    "ponyplay",
    "poof",
    "poon",
    "poontang",
    "punany",
    "poopchute",
    "poopchute",
    "porn",
    "porno",
    "pornography",
    "princealbertpiercing",
    "pthc",
    "pubes",
    "pussy",
    "queaf",
    "queef",
    "quim",
    "raghead",
    "ragingboner",
    "rape",
    "raping",
    "rapist",
    "rectum",
    "reversecowgirl",
    "rimjob",
    "rimming",
    "rosypalm",
    "rosypalmandher5sisters",
    "rustytrombone",
    "sadism",
    "santorum",
    "scat",
    "schlong",
    "scissoring",
    "semen",
    "sex",
    "sexcam",
    "sexo",
    "sexy",
    "sexual",
    "sexually",
    "sexuality",
    "shavedbeaver",
    "shavedpussy",
    "shemale",
    "shibari",
    "shit",
    "shitblimp",
    "shitty",
    "shota",
    "shrimping",
    "skeet",
    "slanteye",
    "slut",
    "s&m",
    "smut",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "spastic",
    "spic",
    "splooge",
    "sploogemoose",
    "spooge",
    "spreadlegs",
    "spunk",
    "strapon",
    "strapon",
    "strappado",
    "stripclub",
    "styledoggy",
    "suck",
    "sucks",
    "suicidegirls",
    "sultrywomen",
    "swastika",
    "swinger",
    "taintedlove",
    "tastemy",
    "teabagging",
    "threesome",
    "throating",
    "thumbzilla",
    "tiedup",
    "tightwhite",
    "titties",
    "titty",
    "tongueina",
    "topless",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "tubgirl",
    "tubgirl",
    "tushy",
    "twink",
    "twinkie",
    "twogirlsonecup",
    "undressing",
    "upskirt",
    "urethraplay",
    "urophilia",
    "vagina",
    "venusmound",
    "viagra",
    "vibrator",
    "violetwand",
    "vorarephilia",
    "voyeur",
    "voyeurweb",
    "voyuer",
    "vulva",
    "wank",
    "wetback",
    "wetdream",
    "whitepower",
    "whore",
    "worldsex",
    "wrappingmen",
    "wrinkledstarfish",
    "yaoi",
    "yellowshowers",
    "yiffy",
    "zoophilia",
    "lolilover",
]

//https://gist.github.com/VikramTiwari/c356e1c16c43614d95e76db311cab3ff
// export const ALLOWED_EMAIL_DOMAINS = [
//     // "gmail.com",
//     // "aol.com",
//     // "att.net",
//     // "comcast.net",
//     // "facebook.com",
//     // "gmx.com",
//     // "googlemail.com",
//     // "google.com",
//     // "hotmail.com",
//     // "hotmail.co.uk",
//     // "mac.com",
//     // "me.com",
//     // "mail.com",
//     // "msn.com",
//     // "live.com",
//     // "sbcglobal.net",
//     // "verizon.net",
//     // "yahoo.com",
//     // "yahoo.co.uk",
//     // /* Other global domains */
//     // "email.com",
//     // "fastmail.fm",
//     // "games.com" /* AOL */,
//     // "gmx.net",
//     // "hush.com",
//     // "hushmail.com",
//     // "icloud.com",
//     // "iname.com",
//     // "inbox.com",
//     // "lavabit.com",
//     // "love.com" /* AOL */,
//     // "outlook.com",
//     // "pobox.com",
//     // "protonmail.ch",
//     // "protonmail.com",
//     // "tutanota.de",
//     // "tutanota.com",
//     // "tutamail.com",
//     // "tuta.io",
//     // "keemail.me",
//     // "rocketmail.com" /* Yahoo */,
//     // "safe-mail.net",
//     // "wow.com" /* AOL */,
//     // "ygm.com" /* AOL */,
//     // "ymail.com" /* Yahoo */,
//     // "zoho.com",
//     // "yandex.com",
//     // /* United States ISP domains */
//     // "bellsouth.net",
//     // "charter.net",
//     // "cox.net",
//     // "earthlink.net",
//     // "juno.com",
//     // /* British ISP domains */
//     // "btinternet.com",
//     // "virginmedia.com",
//     // "blueyonder.co.uk",
//     // "freeserve.co.uk",
//     // "live.co.uk",
//     // "ntlworld.com",
//     // "o2.co.uk",
//     // "orange.net",
//     // "sky.com",
//     // "talktalk.co.uk",
//     // "tiscali.co.uk",
//     // "virgin.net",
//     // "wanadoo.co.uk",
//     // "bt.com",
//     // /* Domains used in Asia */
//     // "sina.com",
//     // "sina.cn",
//     // "qq.com",
//     // "naver.com",
//     // "hanmail.net",
//     // "daum.net",
//     // "nate.com",
//     // "yahoo.co.jp",
//     // "yahoo.co.kr",
//     // "yahoo.co.id",
//     // "yahoo.co.in",
//     // "yahoo.com.sg",
//     // "yahoo.com.ph",
//     // "163.com",
//     // "yeah.net",
//     // "126.com",
//     // "21cn.com",
//     // "aliyun.com",
//     // "foxmail.com",
//     // /* French ISP domains */
//     // "hotmail.fr",
//     // "live.fr",
//     // "laposte.net",
//     // "yahoo.fr",
//     // "wanadoo.fr",
//     // "orange.fr",
//     // "gmx.fr",
//     // "sfr.fr",
//     // "neuf.fr",
//     // "free.fr",
//     // /* German ISP domains */
//     // "gmx.de",
//     // "hotmail.de",
//     // "live.de",
//     // "online.de",
//     // "t-online.de" /* T-Mobile */,
//     // "web.de",
//     // "yahoo.de",
//     // /* Italian ISP domains */
//     // "libero.it",
//     // "virgilio.it",
//     // "hotmail.it",
//     // "aol.it",
//     // "tiscali.it",
//     // "alice.it",
//     // "live.it",
//     // "yahoo.it",
//     // "email.it",
//     // "tin.it",
//     // "poste.it",
//     // "teletu.it",
//     // /* Russian ISP domains */
//     // "mail.ru",
//     // "rambler.ru",
//     // "yandex.ru",
//     // "ya.ru",
//     // "list.ru",
//     // /* Belgian ISP domains */
//     // "hotmail.be",
//     // "live.be",
//     // "skynet.be",
//     // "voo.be",
//     // "tvcablenet.be",
//     // "telenet.be",
//     // /* Argentinian ISP domains */
//     // "hotmail.com.ar",
//     // "live.com.ar",
//     // "yahoo.com.ar",
//     // "fibertel.com.ar",
//     // "speedy.com.ar",
//     // "arnet.com.ar",
//     // /* Domains used in Mexico */
//     // "yahoo.com.mx",
//     // "live.com.mx",
//     // "hotmail.es",
//     // "hotmail.com.mx",
//     // "prodigy.net.mx",
//     // /* Domains used in Canada */
//     // "yahoo.ca",
//     // "hotmail.ca",
//     // "bell.net",
//     // "shaw.ca",
//     // "sympatico.ca",
//     // "rogers.com",
//     // /* Domains used in Brazil */
//     // "yahoo.com.br",
//     // "hotmail.com.br",
//     // "outlook.com.br",
//     // "uol.com.br",
//     // "bol.com.br",
//     // "terra.com.br",
//     // "ig.com.br",
//     // "itelefonica.com.br",
//     // "r7.com",
//     // "zipmail.com.br",
//     // "globo.com",
//     // "globomail.com",
//     // "oi.com.br",
// ]
